import streamlit as st
import re
from utils.page_generator import *
from utils.page_template import *
  
def style_page():
    '''
    Initalizes the content and style for the page text.
    '''
    st.markdown(
        """
        <style>
        .centered {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
        }
        h1 {
            font-size: 70px;
        }
        p.centered {
            font-size: 18px;
            color: #666;
            margin-top: -15px;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )
    # Centered container
    st.markdown('<div class="centered">', unsafe_allow_html=True)
    # Title
    st.markdown('<h1 class="centered">Infipedia</h1>', unsafe_allow_html=True)
    st.markdown('<p class=centered>The Free (infinite) Encyclopedia', unsafe_allow_html=True)


# Search bar
def change_label_style(label, font_size='12px', font_color='white'):
    '''
    A helper function to initalize the style for the search bar label.

    Args:
        :label (str): Value for label css attribute
        :font_size (str): Value for font_size css attribute
        :font_color (str): Value for font_color css attribute
    '''
    html = f"""
    <script>
        var elems = window.parent.document.querySelectorAll('p');
        var elem = Array.from(elems).find(x => x.innerText == '{label}');
        elem.style.fontSize = '{font_size}';
        elem.style.color = '{font_color}';
    </script>
    """
    st.components.v1.html(html)


# Dynamic page creation
def create_new_page(search_query):
    '''
    Creates a new page based on a search query and redirects the user to that page.

    Args:
        :search_query (str): A search query to be parsed as input for content generation
    '''
    # Get title for page
    page_title = generate_title(search_query)

    # Define the file path
    fname = page_title.replace(" ", "")
    file_path = f"pages/{fname}.py"

    # Create new file & write the page content to the file
    with open(file_path, "w") as file:
        gen_content = generate_content(search_query)
        page_content = get_template(content=gen_content)
        
        # Replace delimited text (generated by model) with linked text
        pattern = r"\[\[(.*?)\]\]"
        processed_content = re.sub(pattern, lambda m: f"[{m.group(1)}](?action={m.group(1).replace(" ", "_")})", page_content)
        processed_content = processed_content.replace("$", "\$")
        file.write(processed_content)

    return file_path


def main():
    # Initalizing page content and style
    style_page()
    # Set style for search bar label
    label = "Search and learn something new"
    change_label_style(label, '18px')
    query = st.text_input(label, key="search_query")

    # Read query parameters to handle clicked actions
    query_params = st.query_params
    if query_params.get('action'):
        st.write(f"You clicked the link: {query_params.get('action')}")
        print(f"Clicked link text: {query_params.get('action')}")
        print(query_params.get('action'))
        st.switch_page('pages/Animal.py')

    # Redirect on submit button click
    if st.button("Search"):
        if query:
            file_path = create_new_page(query)
            # Redirect to new page
            st.switch_page(file_path)

    st.markdown('</div>', unsafe_allow_html=True)

if __name__ == "__main__":
    main()